src/wikify/models.py
from django.db import models

class VersionMeta(models.Model):
    """ Additional meta data for revisions. """
    revision = models.ForeignKey("reversion.Revision")
    ip_address = models.IPAddressField()

src/wikify/__init__.py
__all__ = ["wikify"]

def wikify(model_ref):
    def decorator(func):
        def inner(request, *args, **kwargs):
            # Import lazily, so we don't import views directly, saves us some
            # trouble, e.g. https://bitbucket.org/kumar303/fudge/issue/17/module-import-order-influences-whether
            from wikify.views import edit, diff, version, versions

            if isinstance(model_ref, basestring):
                try:
                    module_str, model_str = model_ref.rsplit('.', 1)
                    module = __import__(module_str, fromlist=[model_str])
                    model = getattr(module, model_str)
                except ImportError, e:
                    raise ValueError("Module %s not found: %s"
                                     % (module_str, e))
                except AttributeError:
                    raise ValueError("Module %s has no attribute %s"
                                     % (module_str, model_str))
            else:
                model = model_ref

            # The primary key must be either given by the model field's name, or
            #   simply by Django's standard 'object_id'
            primary_key = model._meta.pk.name
            object_id = kwargs.get(primary_key) or kwargs.get('object_id')

            # Get action
            if request.method == 'POST':
                action = request.POST.get('action')
            else:
                action = request.GET.get('action')

            if action == 'edit':
                return edit(request, model, object_id)
            elif action == 'diff':
                return diff(request, model, object_id)
            elif action == 'version':
                return version(request, model, object_id)
            elif action == 'versions':
                return versions(request, model, object_id)
            else:
                # No valid action given, call decorated view
                return func(request, *args, **kwargs)

        return inner

    return decorator

src/wikify/views.py
from django.shortcuts import render_to_response
from django.http import HttpResponseBadRequest, HttpResponseRedirect, Http404
from django.template import RequestContext
from django.db import transaction
from django.core import paginator
from reversion import models
from reversion import revision

from wikify.models import VersionMeta
from wikify import utils

@transaction.commit_on_success
def edit(request, model, object_id):
    """Edit or create a page."""

    form_class = utils.get_model_wiki_form(model)
    version = None

    if request.method == 'POST':
        try:
            page = model.objects.get(pk=object_id)
        except model.DoesNotExist:
            page = model(pk=object_id)

        form = form_class(request.POST, instance=page)

        if form.is_valid():
            with revision:
                # Save the author, use our metadata model if user is anonymous
                if not request.user.is_anonymous():
                    revision.user = request.user
                else:
                    ip_address = request.META.get('HTTP_X_FORWARDED_FOR',
                                                request.META.get('REMOTE_ADDR'))
                    if ip_address:
                        revision.add_meta(VersionMeta,
                                          ip_address=ip_address)

                # Save a comment for the revision
                if form.cleaned_data.get('wikify_comment'):
                    revision.comment = form.cleaned_data['wikify_comment']

                form.save()

                # Successfully saved the page, now return to the 'read' view
                return HttpResponseRedirect(request.path)
    else:
        if request.GET.get('version_id'):
            # User is editing the page based on an older version
            try:
                version_id = int(request.GET.get('version_id'))
                version = (models.Version.objects.get_for_object_reference(
                                                               model, object_id)
                                         .get(id=version_id))
                page = version.object_version.object
            except (ValueError, models.Version.DoesNotExist):
                raise Http404('Version not found')

            form = form_class(instance=page)
        else:
            try:
                page = model.objects.get(pk=object_id)
                form = form_class(instance=page)
            except model.DoesNotExist:
                form = form_class()

    return render_to_response('wikify/edit.html',
                              {'form': form,
                               'object_id': object_id,
                               'version': version},
                              context_instance=RequestContext(request))

def version(request, model, object_id):
    """Returns a versioned view of the given instance."""
    try:
        version_id = int(request.GET.get('version_id'))
        version = (models.Version.objects.get_for_object_reference(model,
                                                                   object_id)
                                  .get(id=version_id))
        instance = version.object_version.object
    except (ValueError, models.Version.DoesNotExist):
        raise Http404('Version not found')

    return render_to_response('wikify/version.html',
                              {'instance': instance,
                               'fields': list(utils.model_field_iterator(
                                                                     instance)),
                               'version': version},
                              context_instance=RequestContext(request))

def versions(request, model, object_id, paginate=20):
    """Returns a paginated list of all versions of the given instance."""

    all_versions = (models.Version.objects.get_for_object_reference(model,
                                                                    object_id)
                                   .reverse()
                                   .select_related("revision"))
    p = paginator.Paginator(all_versions, paginate)
    page_no = request.GET.get('page', 1)
    try:
        versions = p.page(page_no)
    except paginator.PageNotAnInteger:
        versions = p.page(1)
    except paginator.EmptyPage:
        versions = p.page(p.num_pages)

    return render_to_response('wikify/versions.html',
                              {'object_id': object_id,
                               'versions': versions},
                              context_instance=RequestContext(request))

def diff(request, model, object_id):
    """Returns the difference between the given version and the previous one."""

    versions = models.Version.objects.get_for_object_reference(model, object_id)
    try:
        version_id = int(request.GET.get('version_id'))
        # Get version and make sure it belongs to the given page
        new_version = versions.get(id=version_id)
    except (ValueError, models.Version.DoesNotExist):
        raise Http404("Version not found")

    old_version_q = versions.filter(id__lt=version_id).reverse()
    old_version = old_version_q[0] if old_version_q else None

    # Get the next version so we can provide a link
    next_version_q = versions.filter(id__gt=version_id)
    next_version = next_version_q[0] if next_version_q else None

    context = {'old_version': old_version,
               'new_version': new_version,
               'fields': list(utils.version_field_iterator(old_version,
                                                           new_version)),
               'next_version': next_version}
    return render_to_response('wikify/diff.html',
                              context,
                              context_instance=RequestContext(request))

src/wikify/templates/wikify/base.html
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="{{ STATIC_URL }}wikify/style.css" />
    <title>{% block title %}{{ object_id }}{% endblock %}</title>
</head>

<body>
    {% block content %}{% endblock %}
</body>

src/wikify/templates/wikify/contextual_diff_tr.html
{% load i18n %}
{% for left_line_idx, right_line_idx, diff in context_diff %}
    <tr class="wikify-lineno">
        <td colspan="2">
            {% blocktrans with line=left_line_idx|add:"1" %}Line {{ line }}{% endblocktrans %}
        </td>
        <td colspan="2">
            {% blocktrans with line=right_line_idx|add:"1" %}Line {{ line }}{% endblocktrans %}
        </td>
    </tr>
    {% for left, right in diff %}
        <tr class="{% if left != right %}wikify-change{% else %}wikify-nochange{% endif %}">
            {% if left == None %}
                <td class="wikify-changestatus"></td>
                <td class="wikify-left"></td>
            {% else %}
                <td class="wikify-changestatus">
                    {% if left != right %}-{% endif %}
                </td>
                <td class="wikify-diffcontent wikify-left">{% autoescape off %}{{ left }}{% endautoescape %}</td>
            {% endif %}
            {% if right == None %}
                <td class="wikify-changestatus"></td>
                <td class="wikify-right"></td>
            {% else %}
                <td class="wikify-changestatus">
                    {% if left != right %}+{% endif %}
                </td>
                <td class="wikify-diffcontent wikify-right">{% autoescape off %}{{ right }}{% endautoescape %}</td>
            {% endif %}
        </tr>
    {% endfor %}
{% endfor %}

src/wikify/templates/wikify/diff.html
{% extends "wikify/base.html" %}
{% load url from future %}
{% load i18n markup %}
{% load diff %}
{% block title %}
    {% blocktrans with object_id=new_version.object_id %}Difference for {{ object_id }}{% endblocktrans %}
{% endblock %}

{% block content %}
    <div class="wikify-diff">
        <h1 class="wikify-title">
            {% blocktrans with object_id=new_version.object_id %}Difference for {{ object_id }}{% endblocktrans %}
        </h1>

        <div class="wikify-content">
            <table>
                <thead>
                    <tr class="wikify-navigation">
                        <td class="wikify-old" colspan="2">
                            {% if old_version %}
                                <a href="?action=diff&version_id={{ old_version.id }}">{% trans "previous" %}</a>
                            {% endif %}
                        </td>
                        <td class="wikify-new" colspan="2">
                            {% if next_version %}
                                <a href="?action=diff&version_id={{ next_version.id }}">{% trans "next" %}</a>
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <td class="wikify-old" colspan="2">
                            {% if old_version %}
                                <span class="wikify-date">
                                    <a href="?action=version&version_id={{ old_version.id }}">{{ old_version.revision.date_created|date:"DATETIME_FORMAT" }} ({{ new_version.revision.date_created|date:"T" }})</a>
                                </span>
                                <span class="wikify-user">
                                    {% if old_version.revision.user %}
                                        {% blocktrans with user=old_version.revision.user %}by {{ user }}{% endblocktrans %}
                                    {% else %}
                                        {% blocktrans with user=old_version.revision.versionmeta_set.get.ip_address %}by {{ user }}{% endblocktrans %}
                                    {% endif %}
                                </span>
                                <span class="wikify-comment">{{ old_version.revision.comment }}</span>
                            {% endif %}
                        </td>
                        <td class="wikify-new" colspan="2">
                            <span class="wikify-date">
                                    <a href="?action=version&version_id={{ new_version.id }}">{{ new_version.revision.date_created|date:"DATETIME_FORMAT" }} ({{ new_version.revision.date_created|date:"T" }})</a>
                            </span>
                            <span class="wikify-user">
                                {% if new_version.revision.user %}
                                    {% blocktrans with user=new_version.revision.user %}by {{ user }}{% endblocktrans %}
                                {% else %}
                                    {% blocktrans with user=new_version.revision.versionmeta_set.get.ip_address %}by {{ user }}{% endblocktrans %}
                                {% endif %}
                            </span>
                            <span class="wikify-comment">{{ new_version.revision.comment }}</span>
                        </td>
                    </tr>
                </thead>
                <tbody>
                {% if fields|length == 1 %}
                    {% for field, old_value, new_value in fields %}
                        {% context_diff_tr old_value new_value %}
                    {% endfor %}
                {% else %}
                    {% for field, value in fields %}
                        <tr colspan="4" class="{{ field.name }}">
                            <span class="wikify-label">{{ field.verbose_name|capfirst }}:</span>
                        </tr>
                        {% context_diff_tr old_value new_value %}
                    {% endfor %}
                {% endif %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

src/wikify/templates/wikify/edit.html
{% extends "wikify/base.html" %}
{% load i18n %}
{% block title %}
    {% blocktrans %}Edit "{{ object_id }}"{% endblocktrans %}
{% endblock %}

{% block content %}
    <div class="wikify-edit">
        <h1 class="wikify-title">
            {% blocktrans %}Edit "{{ object_id }}"{% endblocktrans %}
        </h1>

        <div class="wikify-content">
            <form action="" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="hidden" name="action" value="edit" />
                <button type="submit">{% trans "Save" %}</button>
                <a href="?">{% trans "Cancel" %}</a>
            </form>
        </div>
    </div>
{% endblock %}

src/wikify/templates/wikify/version.html
{% extends "wikify/base.html" %}
{% load i18n %}
{% block title %}{{ instance.pk }}{% endblock %}

{% block content %}
    <div class="wikify-version">
        <span class="wikify-date">
            {{ version.revision.date_created|date:"DATETIME_FORMAT"}} ({{ version.revision.date_created|date:"T" }})
        </span>
        <span class="wikify-user">
            {% if version.revision.user %}
                {% blocktrans with user=version.revision.user %}by {{ user }}{% endblocktrans %}
            {% else %}
                {% blocktrans with user=version.revision.versionmeta_set.get.ip_address %}by {{ user }}{% endblocktrans %}
            {% endif %}
        </span>
        <span class="wikify-comment">{{ version.revision.comment }}</span>

        <h1 class="wikify-title">{{ instance.pk }}</h1>

        <a class="wikify-editlink" href="?action=edit&version_id={{ version.id }}">{% trans "edit" %}</a>

        <div class="wikify-content">
            {% if fields|length == 1 %}
                {% for field, value in fields %}
                    <div class="{{ field.name }}">
                        <span class="wikify-value">{{ value }}</span>
                    </div>
                {% endfor %}
            {% else %}
                {% for field, value in fields %}
                    <div class="{{ field.name }}">
                        <span class="wikify-label">{{ field.verbose_name|capfirst }}:</span>
                        <span class="wikify-value">{{ value }}</span>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
{% endblock %}

src/wikify/templates/wikify/versions.html
{% extends "wikify/base.html" %}
{% load i18n %}
{% block title %}
    {% blocktrans %}Versions for "{{ object_id }}"{% endblocktrans %}
{% endblock %}

{% block content %}
    <div class="wikify-versions">
        <h1 class="wikify-title">
            {% blocktrans %}Versions for "{{ object_id }}"{% endblocktrans %}
        </h1>

        <div class="wikify-content">
            <ul class="wikify-dategroup">
            {% regroup versions.object_list by revision.date_created|date:"DATE_FORMAT" as versions_by_date %}
            {% for version_date in versions_by_date %}
                <li>
                    <span class="wikify-date">
                        {{ version_date.grouper }} ({{ version_date.list.0.revision.date_created|date:"T" }})
                    </span>
                    <ul class="wikify-versions">
                    {% for version in version_date.list %}
                        <li>
                            <span class="wikify-timestamp">
                                <a href="?action=version&version_id={{ version.id }}">{{ version.revision.date_created|date:"TIME_FORMAT" }}</a>
                            </span>
                            <span class="wikify-user">
                                {% if version.revision.user %}
                                    {% blocktrans with user=version.revision.user %}by {{ user }}{% endblocktrans %}
                                {% else %}
                                    {% blocktrans with user=version.revision.versionmeta_set.get.ip_address %}by {{ user }}{% endblocktrans %}
                                {% endif %}
                            </span>
                            <span class="wikify-comment">{{ version.revision.comment }}</span>
                            <span class="wikify-difflink"><a href="?action=diff&version_id={{ version.id }}">{% trans "diff" %}</a></span>
                            <span class="wikify-editlink"><a href="?action=edit&version_id={{ version.id }}">{% trans "edit" %}</a></span>
                        </li>
                    {% endfor %}
                    </ul>
                </li>
            {% endfor %}
            </ul>
            <div class="wikify-pagination">
                <span class="wikify-steplinks">
                    {% if versions.has_previous %}
                        <a href="?action=versions&page={{ versions.previous_page_number }}">{% trans "previous" %}</a>
                    {% endif %}

                    <span class="wikify-current">
                        {% blocktrans with no=versions.number count=versions.paginator.num_pages %}Page {{ no }} of {{ count }}.{% endblocktrans %}
                    </span>

                    {% if versions.has_next %}
                        <a href="?action=versions&page={{ versions.next_page_number }}">{% trans "next" %}</a>
                    {% endif %}
                </span>
            </div>
        </div>
    </div>
{% endblock %}